<?php /*%%SmartyHeaderCode:51559262152d75ea048f532-53505410%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '7dfde8e6f0d2939bafae209365617e82615eb8c3' => 
    array (
      0 => './incl/xhtml/default/frontend/united-states-state.tpl',
      1 => 1389072664,
      2 => 'file',
    ),
    '7ed0bd03d771761c7c5f33c327229cb1d136b7d4' => 
    array (
      0 => './incl/xhtml/default/frontend/master.tpl',
      1 => 1388288299,
      2 => 'file',
    ),
    '77288c39bae634b208d74410502963c105e4a942' => 
    array (
      0 => './incl/xhtml/default/frontend/ads-four-square.tpl',
      1 => 1383628110,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '51559262152d75ea048f532-53505410',
  'variables' => 
  array (
    'page' => 1,
    'yr' => 0,
    'bodyclasses' => 0,
    'category' => 0,
    'langprefix' => 0,
    'isUserLoggedIn' => 0,
    'opt' => 1,
    'is_search' => 0,
    'stateitem' => 1,
    'article' => 1,
  ),
  'has_nocache_code' => true,
  'version' => 'Smarty-3.1.8',
  'unifunc' => 'content_52d75ea16547b1_49829325',
  'cache_lifetime' => 900,
),true); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_52d75ea16547b1_49829325')) {function content_52d75ea16547b1_49829325($_smarty_tpl) {?><!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie ie6 no-js" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7 no-js" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8 no-js" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9 no-js" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head id="www-mhsamerica-com" data-template-set="html5-reset">
	<meta charset="utf-8">
		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title><?php if ($_smarty_tpl->tpl_vars['page']->value['title']){?><?php echo $_smarty_tpl->tpl_vars['page']->value['title'];?>
 :: <?php }?>MHS America</title>

	<meta name="title" content="MHS America - <?php echo $_smarty_tpl->tpl_vars['page']->value['meta_title'];?>
">
	<meta name="description" content="<?php echo $_smarty_tpl->tpl_vars['page']->value['meta_description'];?>
The leading search engine for finding vacant spaces as well as services and contractors.">
	<meta name="keywords" content="<?php echo $_smarty_tpl->tpl_vars['page']->value['meta_keywords'];?>
">
	<meta name="google-site-verification" content="">
	<meta name="author" content="MHS America">
	<meta name="Copyright" content="Copyright &copy; 2014 MHS America. All Rights Reserved.">

	<!-- Dublin Core Metadata : http://dublincore.org/ -->
	<link rel="schema.DC" href="http://purl.org/dc/terms/">
	<meta name="DC.title" content="MHS America<?php if ($_smarty_tpl->tpl_vars['page']->value['title']){?> - <?php echo $_smarty_tpl->tpl_vars['page']->value['title'];?>
<?php }?>">
	<meta name="DC.subject" content="Mobile home spaces, contractors, and services">
	<meta name="DC.creator" content="Kage-Mykel Edwards">
	<meta name="viewport" content="width=device-width">
	<!--  Mobile Viewport Fix
	j.mp/mobileviewport & davidbcalhoun.com/2010/viewport-metatag 
	device-width : Occupy full width of the screen in its current orientation
	initial-scale = 1.0 retains dimensions instead of zooming out if page height > device height
	maximum-scale = 1.0 retains dimensions instead of zooming in if page width < device width
	-->
	<!-- Uncomment to use; use thoughtfully!
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	-->

	<link rel="shortcut icon" href="/_/img/favicon.ico">
	<link rel="apple-touch-icon" href="/_/img/apple-touch-icon.png">
	<link href='//fonts.googleapis.com/css?family=Alegreya+Sans' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="/_/css/style.css">
	<link rel="stylesheet" href="/_/kendo/styles/kendo.common.min.css">
    <link rel="stylesheet" href="/_/kendo/styles/kendo.default.min.css">
	<link rel="stylesheet" type="text/css" href="/_/css/zocial.css">
	<link rel="stylesheet" type="text/css" media="screen" href="/_/js/jqvmap/jqvmap.css">
		
<!-- Generated by OpenX 2.8.10 -->
<script type='text/javascript'><!--// <![CDATA[
    var OA_zones = {"zone_2_1":2,"zone_2_2":2,"zone_2_3":2,"zone_2_4":2}    
// ]]> --></script>
<script type='text/javascript' src='http://mhsamerica.metachrys.com/openx/www/delivery/spcjs.php?id=2'></script>

	<script src="/_/js/<?php if ($_smarty_tpl->tpl_vars['page']->value['jquery']){?><?php echo $_smarty_tpl->tpl_vars['page']->value['jquery'];?>
<?php }else{ ?>jquery-1.10.2.min.js<?php }?>"></script>
    <script src="/_/kendo/js/kendo.web.min.js"></script>
	<script src="/_/js/modernizr-1.7.min.js"></script>
	
	<!--[if IE]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	
</head>

<body itemscope itemtype="http://schema.org/WebPage" class="page_state">

<div class="wrapper">
	<header>
		<h1 class="dymaxionscript"><a href="/" title="To the front page">MHS America</a></h1>
		<nav>
			<ul>
				<li class="active"><a href="#">Search Method</a><ul><li><a href="#map">County Map</a></li><?php if ((s('usemetros'))==1&&$_smarty_tpl->tpl_vars['page']->value['metrocount']!=0){?><li><a href="#area">General Area</a></li><?php }?><li><a href="#counties">County Names</a></li><li><a href="#city">City Name</a></li></ul></li><li id="page-direction"></li>
				
							</ul>
		</nav>
		<script type="text/javascript">
			$(document).ready(function(){
				$("nav ul li a").click(function(){
					if($(this).attr("rel")) {
						$("#srcinput").val($(this).attr("rel"));
						$("nav ul li").removeClass("active");
						$(this).parent().addClass("active");
					}
				});
			});
		</script>
	</header>

	<div id="submenu"></div>
	<?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']){?><style type="text/css">
		div#submenu { border-color:#545454; }
	</style><img src="/_/images/backdrops/<?php echo $_smarty_tpl->tpl_vars['page']->value['canvas']['file'];?>
" alt="" id="pagecanvas"<?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']['heightstretch']==1){?> style="height:100%;width:auto;max-width:none;min-width:100%;"<?php }?>><?php }?>
<?php if ($_smarty_tpl->tpl_vars['page']->value['advert']==true){?><aside class="advertisement" id="backdrop"><a href="<?php echo $_smarty_tpl->tpl_vars['page']->value['backdrop']['url'];?>
"><img src="<?php echo $_smarty_tpl->tpl_vars['page']->value['backdrop']['image'];?>
"/></a><?php }?></div>
<div id="content">
<?php if ($_smarty_tpl->tpl_vars['page']->value['advert']==true){?><span class="ad-notice<?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']['blacknotices']==1){?> black<?php }?>" id="advertisement-notice-right">Sponsored Ad</span><span class="ad-notice<?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']['blacknotices']==1){?> black<?php }?>" id="advertisement-notice">Sponsored Ad</span>
<?php }?>
<a name="map" id="map_a" style="display:block;width:0;height:0;position:absolute;top:-100px;"></a>
<style type="text/css">
#label-state { 
<?php if (($_smarty_tpl->tpl_vars['page']->value['state']['labelmargins'])!=''){?>
	margin:<?php echo $_smarty_tpl->tpl_vars['page']->value['state']['labelmargins'];?>
;
<?php }?><?php if (($_smarty_tpl->tpl_vars['page']->value['state']['labelwidth'])!=''){?>
	width:<?php echo $_smarty_tpl->tpl_vars['page']->value['state']['labelwidth'];?>
;
<?php }?> 
}
<?php if (($_smarty_tpl->tpl_vars['page']->value['state']['custommargin'])!=''){?>
div#vmap {
	margin:<?php echo $_smarty_tpl->tpl_vars['page']->value['state']['custommargin'];?>
;
}
<?php }?>
<?php if (($_smarty_tpl->tpl_vars['page']->value['state']['customheight'])!=''){?>
div#vmap {
	min-height:<?php echo $_smarty_tpl->tpl_vars['page']->value['state']['customheight'];?>
 !important;
}
<?php }?>
</style>
<section id="us-map-state">
	<a name="top" id="top_a">&nbsp;</a>
	<span id="label-state"><?php echo $_smarty_tpl->tpl_vars['page']->value['state']['title'];?>
</span>
	<div id="vmap"></div>	
</section>
<section id="business-tiles"><?php if ($_smarty_tpl->tpl_vars['page']->value['pragpage']=="state"){?><?php if ((s('usemetros'))==1&&$_smarty_tpl->tpl_vars['page']->value['metrocount']!=0){?><a name="area" id="area_a"></a><?php }else{ ?><a name="counties" id="counties_a"></a><?php }?><?php }?>
<header<?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']['blacknotices']==1){?> class="black"<?php }?>>Sponsored Advertisements</header>
<?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][0]['id']==0){?><div id="advert-a"><a class="please-add-your-ad-here">Please :3</a></div>
<?php }else{ ?><div id="advert-a"><img src="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][0]['image'];?>
" width="0" height="0"><img src="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][0]['hover'];?>
" width="0" height="0"><a href="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][0]['url'];?>
" target="_blank"><?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][0]['title']!=''){?><?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][0]['title'];?>
<?php }else{ ?>&nbsp;<?php }?></a></div>
<?php }?><?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][1]['id']==0){?><div id="advert-b"><a class="please-add-your-ad-here">Please :3</a></div>
<?php }else{ ?><div id="advert-b"><img src="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][1]['image'];?>
" width="0" height="0"><img src="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][1]['hover'];?>
" width="0" height="0"><a href="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][1]['url'];?>
" target="_blank"><?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][1]['title']!=''){?><?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][1]['title'];?>
<?php }else{ ?>&nbsp;<?php }?></a></div>
<?php }?><?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][2]['id']==0){?><div id="advert-c"><a class="please-add-your-ad-here">Please :3</a></div>
<?php }else{ ?><div id="advert-c"><img src="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][2]['image'];?>
" width="0" height="0"><img src="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][2]['hover'];?>
" width="0" height="0"><a href="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][2]['url'];?>
" target="_blank"><?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][2]['title']!=''){?><?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][2]['title'];?>
<?php }else{ ?>&nbsp;<?php }?></a></div>
<?php }?><?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][3]['id']==0){?><div id="advert-d"><a class="please-add-your-ad-here">Please :3</a></div>
<?php }else{ ?><div id="advert-d"><img src="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][3]['image'];?>
" width="0" height="0"><img src="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][3]['hover'];?>
" width="0" height="0"><a href="<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][3]['url'];?>
" target="_blank"><?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][3]['title']!=''){?><?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][3]['title'];?>
<?php }else{ ?>&nbsp;<?php }?></a></div>
<?php }?>
</section>
<style type="text/css">
<?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][0]['id']!=0){?>
#advert-a a {
  background: url(<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][0]['image'];?>
) center center no-repeat;
}
#advert-a a:hover {
  background: url(<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][0]['hover'];?>
) center center no-repeat;
}<?php }?>
<?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][1]['id']!=0){?>
#advert-b a {
  background: url(<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][1]['image'];?>
) center center no-repeat;
}
#advert-b a:hover {
  background: url(<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][1]['hover'];?>
) center center no-repeat;
}<?php }?>
<?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][2]['id']!=0){?>
#advert-c a {
  background: url(<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][2]['image'];?>
) center center no-repeat;
}
#advert-c a:hover {
  background: url(<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][2]['hover'];?>
) center center no-repeat;
}<?php }?>
<?php if ($_smarty_tpl->tpl_vars['page']->value['ads'][3]['id']!=0){?>
#advert-d a {
  background: url(<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][3]['image'];?>
) center center no-repeat;
}
#advert-d a:hover {
  background: url(<?php echo $_smarty_tpl->tpl_vars['page']->value['ads'][3]['hover'];?>
) center center no-repeat;
}<?php }?>
</style><section id="us-county">
<h1>By City Name</h1>
<div class="padded-cell city-form">
<form action="/query" method="GET">
	<input type="text" name="city" id="citytext">
	<input type="hidden" name="state" value="<?php echo $_smarty_tpl->tpl_vars['page']->value['state']['id'];?>
">
	<input type="submit" value="Search" class="zocial primary" id="citysubmit">
	<style type="text/css">
		.city-form {padding-top:2em;padding-bottom:2em;text-align:center;}
		#citytext {font-size:200%;margin:0 0.5em;}
		#citysubmit {width:120px;height:55px;font-size:160%;margin:0 0.5em;}
	</style>
</form>
</div>
<?php if ((s('usemetros'))==1&&$_smarty_tpl->tpl_vars['page']->value['metrocount']!=0){?><h1><?php echo l('by area');?>
</h1>
<div class="padded-cell">
	<?php  $_smarty_tpl->tpl_vars['county'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['county']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['page']->value['metros']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['county']->key => $_smarty_tpl->tpl_vars['county']->value){
$_smarty_tpl->tpl_vars['county']->_loop = true;
?>
		<div class="city-box">
			<a href="<?php echo s('domain');?>
/region/<?php echo $_smarty_tpl->tpl_vars['county']->value['name'];?>
"<?php if ($_smarty_tpl->tpl_vars['county']->value['commcount']==0&&$_smarty_tpl->tpl_vars['county']->value['procount']==0){?> class="light"<?php }?>><span class="city-title"><?php echo $_smarty_tpl->tpl_vars['county']->value['title'];?>
</span><?php if ((s('tidbits'))==1){?><p><span title="Homes" class="tidbit-homes"><?php echo $_smarty_tpl->tpl_vars['county']->value['homecount'];?>
</span><span title="Spaces" class="tidbit-lots"><?php echo $_smarty_tpl->tpl_vars['county']->value['lotcount'];?>
</span><span title="Professionals" class="tidbit-pros"><?php echo $_smarty_tpl->tpl_vars['county']->value['procount'];?>
</span></p><?php }?></a>
		</div>
	<?php } ?><a name="counties" id="counties_a"></a>
<div class="clearfix"></div>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<?php }?><h1>By County</h1>
<div class="padded-cell">
	<?php  $_smarty_tpl->tpl_vars['county'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['county']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['page']->value['counties']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['county']->key => $_smarty_tpl->tpl_vars['county']->value){
$_smarty_tpl->tpl_vars['county']->_loop = true;
?>
		<div class="city-box">
			<a href="<?php echo s('domain');?>
/state/<?php echo $_smarty_tpl->tpl_vars['county']->value['stateabbr'];?>
/county/<?php echo $_smarty_tpl->tpl_vars['county']->value['name'];?>
"<?php if ($_smarty_tpl->tpl_vars['county']->value['commcount']==0&&$_smarty_tpl->tpl_vars['county']->value['procount']==0){?> class="light"<?php }?>><span class="city-title"><?php echo $_smarty_tpl->tpl_vars['county']->value['title'];?>
</span><?php if ((s('tidbits'))==1){?><p><span title="Homes" class="tidbit-homes"><?php echo $_smarty_tpl->tpl_vars['county']->value['homecount'];?>
</span><span title="Spaces" class="tidbit-lots"><?php echo $_smarty_tpl->tpl_vars['county']->value['lotcount'];?>
</span><span title="Professionals" class="tidbit-pros"><?php echo $_smarty_tpl->tpl_vars['county']->value['procount'];?>
</span></p><?php }?></a>
		</div>
	<?php } ?>
<div class="clearfix"></div>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
</section>

	<footer><form action="/contactmail.php" method="GET">
		<div class="wrapper">
			<div class="grid">
								<div class="g6">
					<h3 class="padded"></h3>
									</div>
				<div class="g6 ticker">
										<h3 id="slogan">Finding spaces for mobile home buyers<br>Filling spaces for mobile home park owners</h3>
					<!-- Thanks Jimmy! -->
									</div>
				<div class="clearfix"></div>
				<div class="g3"><hr><h3>Company</h3>
					<ul>
						<li><a href="/news">News</a></li>
						<li><a href="/about">About Us</a></li>
						<li><a href="/contact">Contact</a></li>
					</ul>
				</div>
				<div class="g3"><hr><h3>Legal</h3>
					<ul>
						<li><a href="/privacy">Privacy Policy</a></li>
						<li><a href="/legal">Terms of Use</a></li>
					</ul>
				</div>
				<div class="g3"><hr><h3>Community</h3>
					<ul>
						<li><a href="/ideas">Ideas and Suggestions</a></li>
						<li><a href="/discuss">Discussions</a></li>
						<li><a href="/connected">Connected</a></li>
					</ul>
				</div>
				<div class="g3"><hr><h3>&middot; &middot; &middot;</h3><p><small><?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']['credit']){?><span style="font-style:italic;">Background image by <?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']['link']&&!$_smarty_tpl->tpl_vars['page']->value['canvas']['courtesy']){?><a href="<?php echo $_smarty_tpl->tpl_vars['page']->value['canvas']['link'];?>
" target="_blank" rel="noindex,nofollow"><?php }?><?php echo $_smarty_tpl->tpl_vars['page']->value['canvas']['credit'];?>
<?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']['link']&&!$_smarty_tpl->tpl_vars['page']->value['canvas']['courtesy']){?></a><?php }?><?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']['courtesy']){?><br>Courtesy of <?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']['link']){?><a href="<?php echo $_smarty_tpl->tpl_vars['page']->value['canvas']['link'];?>
" target="_blank" rel="noindex,nofollow"><?php }?><?php echo $_smarty_tpl->tpl_vars['page']->value['canvas']['courtesy'];?>
<?php if ($_smarty_tpl->tpl_vars['page']->value['canvas']['link']){?></a><?php }?><?php }?>.</span><br><?php }?>Copyright &copy; 2014 MHS America.<br>All Rights Reserved.</small></p></div>
				<div class="clearfix"></div>
				&nbsp;<br>&nbsp;
			</div>
		</div>
		</form>
	</footer>

</div>
	<div class="clearfix"></div>	
</div>
<!-- Javascript -->

	
<script src="/_/js/jqvmap/jquery.vmap.js" type="text/javascript"></script>
<script src="/_/js/jqvmap/maps/united-states/jquery.vmap.<?php echo $_smarty_tpl->tpl_vars['page']->value['state']['name'];?>
.js" type="text/javascript"></script>
<script type="text/javascript">
jQuery('#vmap').vectorMap({
    map: '<?php echo $_smarty_tpl->tpl_vars['page']->value['state']['name'];?>
',
    backgroundColor: null,
    color: 'rgba(74,96,255,0.7)',
    hoverColor: '#2233aa',
    selectedColor: '#00b7ea',
	borderColor: '#ffffff',
	borderWidth: 1,
	borderOpacity: 0.65,
    enableZoom: false,
    showTooltip: true,
    selectedRegion: null,
	onRegionClick: function(element, code, region)
    {
        $('body').append($('<form>').attr('method',"GET").attr('id','link-'+code).attr('action','http://mhsamerica.com/state/<?php echo $_smarty_tpl->tpl_vars['page']->value['state']['abbr'];?>
/county/' + code));
		$('#link-'+code).submit();
    }
});
</script>

<?php if ($_smarty_tpl->tpl_vars['page']->value['pragpage']=="state"){?><script type="text/javascript">
$(document).ready(function(){
	$('a[href^="#"]').on('click',function (e) {
	    e.preventDefault();

	    var target = this.hash,
	    $target = $(target+'_a');

	    $('html, body').stop().animate({
	        'scrollTop': $target.offset().top
	    }, 900, 'swing', function () {
	        window.location.hash = target;
	    });
	});
});
</script><?php }?>

<!-- Piwik -->
<script type="text/javascript"> 
  var _paq = _paq || [];
  _paq.push(['setRequestMethod', 'POST']);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://piwik.mhsamerica.com/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript';
    g.defer=true; g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();

</script>
<noscript><p><img src="//piwik.mhsamerica.com/piwik.php?idsite=1&rec=1" style="border:0" alt="" /></p></noscript>
<!-- End Piwik Code -->

</body>
</html>
<?php }} ?>