{extends file="master.tpl"}
{block "headerincludes"}{literal}
<!-- Generated by OpenX 2.8.10 -->
<script type='text/javascript'><!--// <![CDATA[
    var OA_zones = {"zone_2_1":2,"zone_2_2":2,"zone_2_3":2,"zone_2_4":2}    
// ]]> --></script>
<script type='text/javascript' src='http://mhsamerica.metachrys.com/openx/www/delivery/spcjs.php?id=2'></script>
{/literal}{/block}
{block "menubar"}{/block}
{block "pagedir"}<li class="active"><a href="#">Search Method</a><ul><li><a href="#map">County Map</a></li>{if ('usemetros'|s) == 1 && $page.metrocount != 0}<li><a href="#area">General Area</a></li>{/if}<li><a href="#counties">County Names</a></li><li><a href="#city">City Name</a></li></ul></li><li id="page-direction"></li>{/block}
{block "content"}
<a name="map" id="map_a" style="display:block;width:0;height:0;position:absolute;top:-100px;"></a>
<style type="text/css">
{literal}#label-state { {/literal}
{if ($page.state.labelmargins) != ''}
	margin:{$page.state.labelmargins};
{/if}{if ($page.state.labelwidth) != ''}
	width:{$page.state.labelwidth};
{/if} 
{literal}}{/literal}
{if ($page.state.custommargin) != ''}
{literal}div#vmap {{/literal}
	margin:{$page.state.custommargin};
{literal}}{/literal}
{/if}
{if ($page.state.customheight) != ''}
{literal}div#vmap {{/literal}
	min-height:{$page.state.customheight} !important;
{literal}}{/literal}
{/if}
</style>
<section id="us-map-state">
	<a name="top" id="top_a">&nbsp;</a>
	<span id="label-state">{$page.state.title}</span>
	<div id="vmap"></div>	
</section>
{include "ads-four-square.tpl"}
<section id="us-county">
<h1>{'by city name'|l}</h1>
<div class="padded-cell city-form">
<form action="/query" method="GET">
	<input type="text" name="city" id="citytext">
	<input type="hidden" name="state" value="{$page.state.id}">
	<input type="submit" value="Search" class="zocial primary" id="citysubmit">
	<style type="text/css">{literal}
		.city-form {padding-top:2em;padding-bottom:2em;text-align:center;}
		#citytext {font-size:200%;margin:0 0.5em;}
		#citysubmit {width:120px;height:55px;font-size:160%;margin:0 0.5em;}
	{/literal}</style>
</form>
</div>
{if ('usemetros'|s) == 1 && $page.metrocount != 0}<h1>{'by area'|l}</h1>
<div class="padded-cell">
	{foreach from=$page.metros item=county}
		<div class="city-box">
			<a href="{'domain'|s}/region/{$county.name}"{if $county.commcount == 0 && $county.procount == 0} class="light"{/if}><span class="city-title">{$county.title}</span>{if ('tidbits'|s) == 1}<p><span title="Homes" class="tidbit-homes">{$county.homecount}</span><span title="Spaces" class="tidbit-lots">{$county.lotcount}</span><span title="Professionals" class="tidbit-pros">{$county.procount}</span></p>{/if}</a>
		</div>
	{/foreach}<a name="counties" id="counties_a"></a>
<div class="clearfix"></div>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
{/if}<h1>{'by county'|l}</h1>
<div class="padded-cell">
	{foreach from=$page.counties item=county}
		<div class="city-box">
			<a href="{'domain'|s}/state/{$county.stateabbr}/county/{$county.name}"{if $county.commcount == 0 && $county.procount == 0} class="light"{/if}><span class="city-title">{$county.title}</span>{if ('tidbits'|s) == 1}<p><span title="Homes" class="tidbit-homes">{$county.homecount}</span><span title="Spaces" class="tidbit-lots">{$county.lotcount}</span><span title="Professionals" class="tidbit-pros">{$county.procount}</span></p>{/if}</a>
		</div>
	{/foreach}
<div class="clearfix"></div>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
</section>
{/block}
{block "endscripts"}	
<script src="/_/js/jqvmap/jquery.vmap.js" type="text/javascript"></script>
<script src="/_/js/jqvmap/maps/united-states/jquery.vmap.{$page.state.name}.js" type="text/javascript"></script>
<script type="text/javascript">
jQuery('#vmap').vectorMap({
    map: '{$page.state.name}',
    backgroundColor: null,
    color: 'rgba(74,96,255,0.7)',
    hoverColor: '#2233aa',
    selectedColor: '#00b7ea',
	borderColor: '#ffffff',
	borderWidth: 1,
	borderOpacity: 0.65,
    enableZoom: false,
    showTooltip: true,
    selectedRegion: null,
	onRegionClick: function(element, code, region)
    {
        $('body').append($('<form>').attr('method',"GET").attr('id','link-'+code).attr('action','{'domain'|s}/state/{$page.state.abbr}/county/' + code));
		$('#link-'+code).submit();
    }
});
</script>
{/block}
